### ISSUE TITLE
UpdatePassword (mobile/email) with an AuthToken mandatory

### ISSUE THREAD

**Issue by dirceudn** [ReachFive/identity-android-sdk#39]
Currently, in the version 5.0.0 of ReachFive SDK the update password method accepts authToken as one of the required parameters. 
Like the code below:

```
// Update the password with a verification code retrieved from an email
client.updatePassword(
    authToken = profileAuthToken,
    updatePhoneNumberRequest = UpdatePasswordRequest.EmailParams("john.doe@example.com", "234", "ZPf7LFtc"),
    successWithNoContent = { _ -> // Do something },
    failure = { error -> // Return a ReachFive error }
)
```

```
// Update the password with a verification code retrieved from an SMS
client.updatePassword(
    authToken = profileAuthToken,
    updatePhoneNumberRequest = UpdatePasswordRequest.SmsParams("+33682234940", "234", "ZPf7LFtc"),
    successWithNoContent = { _ -> // Do something },
    failure = { error -> // Return a ReachFive error }
)

```
The authToken is retrieved after login but if you forgot your password how can you login to recover the authToken?
One good solution I think would be for the requestPasswordReset to return an authToken for a use in the updatePassword.

**Comment by roxanemace** [comment]
Hi @dirceudn ,

Thank you for reporting the issue. When you update a password with a `verificationCode`, you don't need indeed an `authToken`. I'll release as soon as possible a `5.0.1` version with the fix.

**Comment by roxanemace** [comment]
Hi @dirceudn, [`v5.0.1`](https://github.com/ReachFive/identity-android-sdk/releases/tag/v5.0.1) was released with your fix.

**Comment by dirceudn** [comment]
Thanks :)
