### ISSUE TITLE
ProfileAddress with optional attributes

### ISSUE THREAD

**Issue by dirceudn** [ReachFive/identity-android-sdk#58]
In the last version of reach five SDK documentation the Profile Address is described with some attributes optional. 
https://developer.reach5.co/api/identity-android/#profile-address

But in the ReachFive SDK 5.3.0 we have all attributes of the ProfileAddress required like this:

```
@Parcelize
data class ProfileAddress(
    val title: String?,
    @SerializedName("is_default")
    val isDefault: Boolean?,
    @SerializedName("address_type")
    val addressType: String?,
    @SerializedName("street_address")
    val streetAddress: String?,
    val locality: String?,
    val region: String?,
    @SerializedName("postal_code")
    val postalCode: String?,
    val country: String?,
    val raw: String?,
    @SerializedName("delivery_note")
    val deliveryNote: String?,
    val recipient: String?,
    val company: String?,
    @SerializedName("phone_number")
    val phoneNumber: String?
) : Parcelable
```
If I put an empty String in the attributes I will get an error when updating the profile.
@roxanemace

**Comment by roxanemace** [comment]
Hi @dirceudn, could you send me the response error, please?

**Comment by dirceudn** [comment]
Hi @roxanemace the error is :server_error 500.

**Comment by roxanemace** [comment]
I've found the issue, I'll release a fix soon.

**Comment by dirceudn** [comment]
@roxanemace Thank you :D

**Comment by roxanemace** [comment]
Hi @dirceudn, I've fixed some issues with the `ProfileAddress` model with the new version [`v5.3.1`](https://github.com/ReachFive/identity-android-sdk/releases/tag/v5.3.1) of the SDK. 
I've also specified in the documentation that some fields (`title`, `streetAddress` and `country`) can't be empty strings although they are optional (with the new fixes you should see an explicit error message).

**Comment by dirceudn** [comment]
Thank you @roxanemace :D
