### ISSUE TITLE
signedUid is null

### ISSUE THREAD

**Issue by dirceudn** [ReachFive/identity-android-sdk#64]
Hi,

#### When I retrieve a profile I always see a signed Uid null. This is normal?
`Profile(uid=AWxHjC3mpj2ZiTp0e815, signedUid=null, givenName=null, middleName=null, familyName=Teixeira, name=Teixeira, nickname=null, birthdate=2018-01-01, profileURL=null, picture=null, externalId=null, authTypes=[password], loginSummary=LoginSummary(firstLogin=1564568465101, lastLogin=1566826902757, total=30, origins=[], devices=[android], lastProvider=password), username=null, gender=male, email=dirceu@yopmail.com, emailVerified=true, emails=Emails(verified=[dirceu@yopmail.com], unverified=[]), phoneNumber=null, phoneNumberVerified=null, addresses=null, locale=120 rue jean Jaurès, bio=null, customFields=null, consents=null, tosAcceptedAt=null, createdAt=2019-07-31T10:21:04.868Z, updatedAt=2019-08-26T13:41:42.757Z, liteOnly=false, company=null)`

Thanks :D

**Comment by axuan25** [comment]
Hi @dirceudn,

Thanks for bringing this to our attention.

This field will be removed in the next iteration, you can ignore it for now!

Kind regards,
Chris

**Comment by dirceudn** [comment]
Hi @axuan25,
OK. You're welcome :D .

Thanks[],
