### ISSUE TITLE
user is null authToken reach5.signup

### ISSUE THREAD

**Issue by dirceudn** [ReachFive/identity-android-sdk#69]
Hi,

It's me again sorry =P . When I try a signup like this:

 ```
 reach5.signup(profile, scope = listOf("offline_access", "full_write"), success = { token ->
            Timber.tag (TAG ).e("Success signup = $token")
            handleSignupProcess(username, password, token)
        }, failure = {
            //fixme check the good code error
            Timber.tag(TAG).e("Failure signup = ${it.data}")
        }
        )
```
The user included in the authToken is null:

`AuthToken(idToken=null, accessToken=/*this token is working well but it's too long to type here*/, tokenType=Bearer, expiresIn=86400, user=null)`

Thanks :D

**Comment by axuan25** [comment]
Hi @dirceudn, thanks for reaching out to us.

The `AuthToken.user` field is actually derived from the ID token (`AuthToken.idToken`), which itself is obtained when the `openid` scope is requested.

Retry with the `openid` scope and `AuthToken.user` will be defined!

I hope that helps :)

**Comment by dirceudn** [comment]
Hi,

Okay. Thanks :D
