### ISSUE TITLE
Signup error CertPathValidatorException 

### ISSUE THREAD

**Issue by dirceudn** [ReachFive/identity-android-sdk#70]
Hello,

This morning I couldn't finish the signup. There is an error like this:

`ReachFiveError(message=java.security.cert.CertPathValidatorException: Trust anchor for certification path not found., code=null, exception=null, data=null)`

What does this mean exactly?

Thanks :D

**Comment by axuan25** [comment]
Hi @dirceudn ,

This is most likely related to your specific environment.

For this type of issue, please contact our customer support directly as they will have more information regarding your environment's specifics.

Thanks,
Christopher
