### ISSUE TITLE
Invalid consents with error details null

### ISSUE THREAD

**Issue by dirceudn** [ReachFive/identity-android-sdk#75]
Hi,

When I try update a user profile with a consent there is an error like this:

`ReachFiveError(message=invalid_request, code=400, exception=null, data=ReachFiveApiError(error=invalid_request, errorId=y1l8W30tLL, errorUserMsg=null, errorDescription=Invalid consents, errorDetails=null))`

Here's my code:

```
val inputOffer: String = if (offerAcepted) "opt-in" else "opt-out"
val consent: MutableMap<String, Consent> = mutableMapOf()

val currentConsent = Consent(offerAcepted, inputOffer, PhoneUtils.INSTANCE.getCurrentDate())
consent["optin_newsletter"] = currentConsent

val profile = Profile(gender = gender, givenName = name, familyName = lastName,
                birthdate = date, customFields = fields, addresses = listOfAddress, consents = consent)

reach5.updateProfile(token!!, profile = profile, success = {
     Timber.tag(TAG).d("Profile $it")
        handleReachFIveSuccess()
    }, failure = { error ->
     handleReachFiveError(error)
   })
```

Thanks,

**Comment by dirceudn** [comment]
Here's my code:

```
reach5.updatePhoneNumber(authToken = token, phoneNumber = "0659936987", success = {
                    attachedView?.onChangePhoneNumberSuccess(username, actionState)
                }, failure = { error ->
                    handleFailure(error)

                })
```

Today I have another error:

`ReachFiveError(message=server_error, code=500, exception=null, data=ReachFiveApiError(error=server_error, errorId=SO3mz452EZ, errorUserMsg=null, errorDescription=Unexpected error occurred, errorDetails=null))`

**Comment by roxanemace** [comment]
Hi @dirceudn,
I agree the error doesn't help 😞 
I've tried to reproduce your error and I get the same message when the consent's date is in the future. Could you check please if it's your case?

**Comment by dirceudn** [comment]
Hi @roxanemace. Thanks for your answer. I'm working on it. :D

**Comment by dirceudn** [comment]
Hi @roxanemace. The updateProfile() with the consents it's working well in my tests.

Thanks,
