### ISSUE TITLE
startPasswordless redirect uri is not allowed

### ISSUE THREAD

**Issue by dirceudn** [ReachFive/identity-android-sdk#76]
Hi,

I have an issue related to startPasswordless. When I call the method I have this error message:

`ReachFiveError(message=access_denied, code=403, exception=null, data=ReachFiveApiError(error=access_denied, errorId=r6iYJtOkHn, errorUserMsg=null, errorDescription=The redirect uri is not allowed, errorDetails=null))`

Is there any special setting to do on the reachFive console or SDK ???

Thanks,

**Comment by AnneReach5** [comment]
Hi, 

this issue has been fixed. (Release v5.4.1 - 23/09/2019 : 
https://github.com/ReachFive/identity-android-sdk/blob/master/CHANGELOG.md )

**Comment by dirceudn** [comment]
Thanks
