### ISSUE TITLE
 SMS Fails to Send - Twilio configuration

### ISSUE THREAD

**Issue by dirceudn** [ReachFive/identity-android-sdk#83]
Hi,

There is a bug related to send SMS .It's not working when the user calls the signup() or the startPasswordless() with a phone number.

The error message is -> missing_config (Twilio not configured)

**Comment by AnneReach5** [comment]
Hi, 

You need to configure your SMS provider solution (Twilio or Generic SMS API)  in the ReachFive Back-office
